services:
  Dbp\Relay\KeycloakBundle\Keycloak\KeycloakBearerAuthenticator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\KeycloakBundle\Keycloak\KeycloakBearerUserProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\KeycloakBundle\Service\KeycloakUserSession:
    autowire: true
    autoconfigure: true

  Dbp\Relay\KeycloakBundle\Keycloak\KeycloakBearerUserProviderInterface:
    '@Dbp\Relay\KeycloakBundle\Keycloak\KeycloakBearerUserProvider'

  Dbp\Relay\CoreBundle\API\UserSessionInterface:
    '@Dbp\Relay\KeycloakBundle\Service\KeycloakUserSession'

  Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
    '@Dbp\Relay\KeycloakBundle\Keycloak\KeycloakBearerAuthenticator'
