services:
  Dbp\Relay\AuthBundle\Authenticator\BearerAuthenticator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\Authenticator\BearerUserProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\Service\OIDCUserSessionProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\Authenticator\OIDCUserSessionProviderInterface:
    '@Dbp\Relay\AuthBundle\Service\OIDCUserSessionProvider'

  Dbp\Relay\AuthBundle\OIDC\OIDProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\Authenticator\BearerUserProviderInterface:
    '@Dbp\Relay\AuthBundle\Authenticator\BearerUserProvider'

  Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
    '@Dbp\Relay\AuthBundle\Authenticator\BearerAuthenticator'

  Dbp\Relay\AuthBundle\Service\DefaultUserRoles:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\AuthBundle\API\UserRolesInterface:
    '@Dbp\Relay\AuthBundle\Service\DefaultUserRoles'
